apiVersion: v1
kind: Service
metadata:
  name: kong-service-external
  labels:
    app: kong-deployment
spec:
  type: LoadBalancer
  ports:
    - port: 8000
  selector:
    name: kong-deployment

apiVersion: v1
kind: Service
metadata:
  name: kong-service-internal
  labels:
    app: kong-deployment
spec:
  type: ClusterIP
  ports:
    - port: 8001
  selector:
    name: kong-deployment
