apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  labels:
    app: kong-root
    component: konga
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: konga
  template:
    metadata:
      labels:
        name: konga
    spec:
      containers:
        - name: konga
          image: 422635720234.dkr.ecr.sa-east-1.amazonaws.com/konga:next
          # command:
          #   [
          #     "node ./bin/konga.js  prepare --adapter postgres --uri postgresql://bycoders:bycoders123@10.100.97.242:5432/konga",
          #   ]
          env:
            - name: DB_HOST
              value: 10.100.97.242
            - name: DB_ADAPTER
              value: postgres
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-creds-konga
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-creds-konga
                  key: password
            - name: TOKEN_SECRET
              value: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
            - name: DB_DATABASE
              value: konga
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: 1337
              name: konga
      restartPolicy: Always
