apiVersion: v1
kind: Service
metadata:
  namespace: kong
  name: kong-pgpool-service
  labels:
    name: database-balancer
    node: pgpool
    system: kong
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: database-balancer
    node: pgpool
    system: kong