apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-konga-db-node-1
  labels:
    node: node-1
    system: konga-db
    namespace: application-master
    type: amazonEBS
spec:
  accessModes:
  - ReadWriteMany
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0bc02196ab67d8e79
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Delete
