apiVersion: v1
kind: Service
metadata:
  namespace: konga
  name: konga-db
  labels:
    name: database
    system: konga
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: database
    system: konga
    