apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    node: node5
    system: application-db
    namespace: application-master
    type: amazonEBS
  name: pv-application-db-node5
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-029fc3793613ec40b
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
