apiVersion: v1
kind: Service
metadata:
  namespace: konga
  name: konga-pgpool
  labels:
    name: database-balancer
    node: pgpool
    system: konga
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: database-balancer
    node: pgpool
    system: konga